// config/disclaimer.js
// ─── Clinical Disclaimer · AmbientScribe ─────────────────────────────────────
// This is NOT a substitute for a lawyer-reviewed Terms of Service.
// It is a clear, honest statement of what the product is and isn't,
// displayed to every user before they can sign their first note.
// Get this reviewed by a lawyer before scaling past your first paying users —
// but having this live today is far better than having nothing.
'use strict';

const CLINICAL_DISCLAIMER = {
  version: '1.0',
  effectiveDate: '2026-06-19',

  shortVersion: 'AmbientScribe is an administrative documentation assistant. It does not practice medicine, diagnose patients, or replace clinical judgment. The signing physician is solely responsible for the accuracy and clinical appropriateness of every note before it becomes part of the medical record.',

  fullText: `
CLINICAL DECISION SUPPORT DISCLAIMER

AmbientScribe AI is an administrative documentation tool designed to assist licensed healthcare providers in generating clinical notes. By using this software, you acknowledge and agree to the following:

1. NOT A MEDICAL DEVICE OR PRACTITIONER
AmbientScribe AI does not practice medicine, provide medical advice, or make diagnostic decisions. It is a documentation assistant only. All clinical judgment, diagnosis, and treatment decisions remain solely the responsibility of the licensed healthcare provider using this software.

2. AI-GENERATED CONTENT MAY CONTAIN ERRORS
The SOAP notes, billing codes, clinical decision support suggestions, and safety audit results generated by this software are produced by artificial intelligence and may contain inaccuracies, omissions, or fabricated details not present in the original consultation ("hallucinations"). This is a known limitation of current AI technology.

3. MANDATORY HUMAN REVIEW
No AI-generated note may be considered final, complete, or part of the official medical record until it has been reviewed, corrected as necessary, and explicitly signed by a licensed healthcare provider. The signing action constitutes the provider's professional attestation that they have reviewed the note in full and approve its accuracy.

4. THE SAFETY AUDIT IS A SUPPLEMENTARY AID, NOT A GUARANTEE
The CMO Safety Audit feature is designed to flag potential allergy conflicts and exam-diagnosis contradictions as an additional layer of review. It is not exhaustive, may miss issues, and does not replace the provider's own clinical review. Overriding a flagged conflict transfers full responsibility for that decision to the signing provider.

5. FULL LIABILITY RESTS WITH THE SIGNING PROVIDER
By signing a note within this software, the healthcare provider takes full professional and legal responsibility for its contents, exactly as if they had typed it themselves without AI assistance.

6. NOT FDA-CLEARED OR EQUIVALENT REGULATORY APPROVAL
AmbientScribe AI has not been evaluated or cleared by the FDA or equivalent regulatory bodies as a medical device, because it does not function as one. It is positioned and used strictly as administrative documentation software.

7. NO WARRANTY OF FITNESS FOR ANY SPECIFIC CLINICAL OUTCOME
This software is provided "as is." AmbientScribe AI and its developers make no warranty that use of this software will prevent documentation errors, billing errors, or any adverse clinical outcome.

By clicking "I Acknowledge" or by signing your first note, you confirm that you are a licensed healthcare provider, that you have read and understood this disclaimer, and that you accept full professional responsibility for all content you approve and sign within this software.
  `.trim(),

  requiresAcknowledgment: true, // must be shown + accepted before first note sign
};

module.exports = { CLINICAL_DISCLAIMER };
